apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: spaceport.azurecr.io/galactica
  digest: sha256:c2afe7f7724519629304072b1c2b72749b88c761473b690a94fc203e42f4f707
