apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
- ../../base
images:
- name: spaceport.azurecr.io/galactica
  digest: sha256:cfdb01893ed9ef5c268619b9d7e93b5a568f1ece549dd07d569cd3ff7d51e634
